version: '3.8'

services:
  check-register-frontend:
    container_name: check-register-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - check-register-backend

  check-register-backend:
    container_name: check-register-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database